/** The chat bot service generated by API from https://brainshop.ai/
 The AI chat bot code implementation is from
 https://www.geeksforgeeks.org/how-to-create-a-chatbot-in-android-with-brainshop-api/

**/

package com.example.pandacare.PandaChat;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;

import com.example.pandacare.R;


public class PandaChat extends AppCompatActivity {

    // initialising variables for widgets in xml file
    private RecyclerView chatsRV;
    private ImageButton sendMsgIB;
    private EditText userMsgEdt;
    private final String USER_KEY = "user";
    private final String BOT_KEY = "bot";

    // creating a variable for volley request queue
    private RequestQueue mRequestQueue;

    // creating a variable for array list and adapter class
    private ArrayList<ChatModal> chatModalArrayList;
    private ChatRVAdapter chatRVAdapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_panda_chat);

        // initialising all the views
        chatsRV = findViewById(R.id.idRVChats);
        sendMsgIB = findViewById(R.id.idIBSend);
        userMsgEdt = findViewById(R.id.idEdtMessage);

        // initialise request queue
        mRequestQueue = Volley.newRequestQueue(PandaChat.this);
        mRequestQueue.getCache().clear();

        // creating a new array list
        chatModalArrayList = new ArrayList<>();

        // add on click listener for send message button
        sendMsgIB.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // checking if the message entered by user is empty or not
                if (userMsgEdt.getText().toString().isEmpty()) {
                    Toast.makeText(PandaChat.this, "Please enter your message..", Toast.LENGTH_SHORT).show();
                    return;
                }

                // calling a method to send message to bot to get response
                sendMessage(userMsgEdt.getText().toString());

                // below line are setting text in our edit text as empty
                userMsgEdt.setText("");

                //Make the keyboard close down after sending the message
                InputMethodManager manager = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
                manager.hideSoftInputFromWindow(userMsgEdt.getWindowToken(),0);

            }
        });

        // below line is initialising adapter class and passing our array list to it
        chatRVAdapter = new ChatRVAdapter(chatModalArrayList, this);

        // below line is creating a variable for the linear layout manager
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(PandaChat.this, RecyclerView.VERTICAL, false);

        // here is to set layout manager to the recycler view
        chatsRV.setLayoutManager(linearLayoutManager);

        // here is setting adapter to the recycler view
        chatsRV.setAdapter(chatRVAdapter);

    }

    private void sendMessage(String userMsg) {
        //  pass message to the array list which is entered by the user
        chatModalArrayList.add(new ChatModal(userMsg, USER_KEY));
        chatRVAdapter.notifyDataSetChanged();

        // url for the brainshop.ai
        String url = "http://api.brainshop.ai/get?bid=170972&key=dDVqHKJ0jVrILpGI&uid=uid&msg=" +userMsg;

        // creating a variable for the request queue
        RequestQueue queue = Volley.newRequestQueue(PandaChat.this);

        // below line are making a json object request for a get request and passing in the API url
        JsonObjectRequest jsonObjectRequest = new JsonObjectRequest(Request.Method.GET, url, null, new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(JSONObject response) {
                try {
                    // on response method are extracting data from json response and adding this response to array list
                    String botResponse = response.getString("cnt");
                    chatModalArrayList.add(new ChatModal(botResponse, BOT_KEY));

                    // notifying adapter as data changed
                    chatRVAdapter.notifyDataSetChanged();

                    // the chat view will update and scroll to the most bottom
                    chatsRV.smoothScrollToPosition(chatsRV.getAdapter().getItemCount()-1);
                } catch (JSONException e) {
                    e.printStackTrace();

                    // handling error response from bot
                    chatModalArrayList.add(new ChatModal("No response", BOT_KEY));
                    chatRVAdapter.notifyDataSetChanged();

                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                // error handling
                chatModalArrayList.add(new ChatModal("Sorry no response found", BOT_KEY));
                Toast.makeText(PandaChat.this, "No response from the bot..", Toast.LENGTH_SHORT).show();
            }
        });

        // at last adding json object request to the queue
        queue.add(jsonObjectRequest);
    }
}